---
date: "2019-07-23"
lastmod: "2019-07-23"
slug: "start_tech_blog"
title: "技術ブログ始めます"
thumbnail: ""
description: ""
tags: ["雑記"]
archives: ["2019/07"]
---

[%hardbreaks]
タイトル通りですが、技術ブログを始めます。
始めるきっかけとか、経緯などを書きたいと思います。

== About ME

=== 略歴

* ソフトウェアエンジニア（SES契約が主流）として15年を迎える
* 年齢も40歳をついに迎える
* 子供は娘２人

[%hardbreaks]
時が経つのは早いもので・・・
時代も平成から令和に変わり、私の中でターニングポイントの時期な気がしました。

=== 最近の仕事内容

* 顧客との仕様調整
* 見積やスケジュール調整
* メンバーのフォローや成果物レビュー

[%hardbreaks]
基本的にはこの仕事が主体となり、プログラムをガリガリ書きことも少なくなりました。
少し前までは、年齢（経験）とともに、こういう仕事になることを私自身受け入れたつもりでした。
ただ、数年続けた結果、ぶっちゃけて言うと、日々の仕事に面白さを感じなくなり、物足りなさを感じるようになりました。

== 最近の気になるニュース

一方で、最近こんな記事を見かけます。

* https://headlines.yahoo.co.jp/article?a=20190422-00010000-flash-peo[早期退職しない限り面接が続き…「45歳以上クビ切り」横行中, window="_blank"]
* https://programming-dojo.com/既に始まっているsierの没落/[既に始まっているSierの没落, window="_blank"]
* https://nikkan-spa.jp/1569100[45歳以上はクビ!? NEC、富士通、コカ・コーラetc.でリストラが進行中, window="_blank"]

[%hardbreaks]
最初は他人事のように読んでいた記事ですが、
ふと我に返って冷静に考えると、あと5年を今のようなモチベーションで働き続けてしまったら・・
と、危機感を覚えるようになりました。

== じゃ、プライベートで開発をすればいい

[%hardbreaks]
そう。家で勉強すればいい。プライベートで開発すればいい。
日々、気になる技術系記事は https://qiita.com/[Qiita, window="_blank"] や、 https://b.hatena.ne.jp/hotentry/it[はてブ, window="_blank"] などを読んだり、後でじっくり読みたい記事は https://getpocket.com/[Pocket, window="_blank"] している。
ネタはいくらでもある。

残念ながら・・・プライベートでのアウトプットほとんど出来ていない・・・

[%hardbreaks]
平日は、残業とかで帰宅が遅めになり疲れていてやる気がおきない・・
土日は、子供と遊んだり、家事を手伝ったりで昼間は時間がとれず、夜は疲れてすぐ寝てしまう・・

そういうサイクルの生活を続けて、特に改善させることもなく、数年が経ってしまった。

== というわけで

[%hardbreaks]
そんな経緯があって、今後の自分のエンジニア人生に危機感を覚えたため、技術ブログを書くことに決めました。
技術系情報をインプットしただけではダメなので、アウトプットするために。

まずは、平日は極力残業せずに早めに帰宅して、プライベート開発に時間を取るようにしていく習慣をつけようと思います。
