baseurl = "https://syocky.netlify.com/"
title = "syocky tech blog"
theme = "hugo_theme_robust"
languageCode = "ja-JP"
hasCJKLanguage = true
disqusShortname = "syocky"
googleAnalytics = "UA-139651310-1"

[taxonomies]
  tag = "tags"
  archive = "archives"

[params]
  description = "個人開発における知見のアウトプット化"
  dateformat = "2006-01-02" # Optional
  # Fonts settings.
  googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  logofontfamily = "Lobster, cursive" # Optional, Override logo font.

[params.author]
  thumbnail = "images/logo.jpg"
  name = "syocky"
  description = "<p>Software Engineer@Fukuoka</p>"
  facebook = "https://www.facebook.com/syocky"
  twitter = "https://twitter.com/syocky"
  github = "https://github.com/syocky"
  mail = "https://docs.google.com/forms/d/e/1FAIpQLScFcxHgR4OGrRD21ognPF9CHcQdecmvfJyMdkptrR2IiXkvCQ/viewform?usp=sf_link"

[outputs]
  page = [ "HTML", "AMP" ] # if you want AMP enable.

[permalinks]
  blog = "/blog/:year/:month/:day/:slug/"
