---
date: "2020-01-12"
lastmod: "2020-01-12"
slug: "this-year-resolutions"
title: "今年の抱負"
thumbnail: ""
description: ""
tags: ["雑記","アジャイル開発"]
archives: ["2020/01"]
---

[%hardbreaks]
あけましておめでとうございます。
仕事始めから１週間経ちましたが、今年の抱負を掲げてみたいと思います。

== アジャイル開発手法の実践

[%hardbreaks]
link:/blog/2019/12/27/changed-job/[前回の記事^] で書きましたが、昨年11月に転職しました。
今後はPM/PLというポジションで仕事をしていくキャリアプランを描いています。

[%hardbreaks]
現在のオフィスの開発チームは割と少人数で行っているようです。
そのため、従来のウォーターフォール型の開発手法より、アジャイル開発手法が合っているように思えます。

じゃ、アジャイル開発手法って、どういうのがあって、どう実践していくのが効果的か、などのナレッジ・ノウハウが私には不足しています。

まずは、アジャイル開発手法のナレッジを蓄積するために技術書を読み、少しずつ学んだことを実践していきたいと思います。

今は、入門として読みやすそうな本を読んでいます。

// {{< amazon category="book" key="SCRUM BOOT CAMP THE BOOK" >}}

// {{< amazon category="book" key="カイゼン・ジャーニー たった1人からはじめて、「越境」するチームをつくるまで" >}}

* https://www.amazon.co.jp/gp/product/4798129712/[SCRUM BOOT CAMP THE BOOK^]
* https://www.amazon.co.jp/gp/product/B078HZKLMB/[カイゼン・ジャーニー たった1人からはじめて、「越境」するチームをつくるまで^]

どちらも、システム開発現場をストーリー仕立てでスクラム開発の手法を解説しているため、非常に読みやすく、入門書としては最適だなと思いました。

== 技術書を読んだらアウトプットする

技術書を読むことが好きなので、手元には今読んでいる技術書が１～２冊はある状態にしています。

ただ、技術書を１回読んだら、次の本を読むというサイクルになっているため、１つ１つの本の理解が浅い気がしています。

[%hardbreaks]
このブログを立ち上げたので、今年は技術書を１回読んだら、その本の要約・要点をまとめたブログを書く習慣をつけたいと思います。
ブログを書く際に、もう１回本を読み直すことになるので、より本への理解が深まるかなと思っています。

== Gitコマンドまとめ

11月に転職する前の１ヶ月間（10月）は、まるまる有給消化で休んでいました。

時間があったので、まずは転職先でやることが決まっていたRPA開発を勉強するため、 https://www.uipath.com/ja/rpa/academy[UiPathアカデミー^] をするのと、以前からやろうと思っていた、Gitをきちんと理解することを始めました。

今まで実業務でもGitは使ってましたが、基本的な概念とコマンド程度の理解でやっていたので、もう少し深堀りして理解したいと思ってました。

Gitは学習コストが高く、非常に奥が深いツールだと思っているので、Gitについて学習したら、このブログでまとめ記事を書くつもりでいました。

[%hardbreaks]
10月時点は、Gitについてある程度学習できましたが、予想以上にUiPathアカデミーのボリュームが大きかったので、まとめ記事を書くところまでできませんでした。
なので、近いうちにGitまとめ記事を書こうと思っています。

== Python入門

最近、弊社マネージャと1on1面談したときに、Pythonを使った開発の話があるけど、うちの開発メンバに経験者がいないという話を聞きました。

転職前にもPythonの仕事がここ数年多くなっているという話を聞いていたので、Pythonの需要が増えてきている印象があります。

[%hardbreaks]
個人的にも新しい言語を習得したいなと思っていて、Go言語を本格的に勉強しようと考えていました。
だいぶ前（４、５年前）くらいに、 https://go-tour-jp.appspot.com/list[A Tour of Go^] をやった程度で終わっていたので・・

[%hardbreaks]
ただ、身近にPythonの需要が増えている状況から、Pythonを優先的に勉強した方がいいと考えるようになり、今年はPythonの基礎学習をしたいと思います。
とりあえず、ざっと調べた感じ、下記の入門書が良さそうだったので、これで勉強しようと考えています。

//{{< amazon category="book" key="入門 Python 3" >}}
https://www.amazon.co.jp/gp/product/4873117380/[入門 Python 3^]

余裕があれば、こちらも読んで理解を深めたいと思っています。

// {{< amazon category="book" key="Effective Python ―Pythonプログラムを改良する59項目" >}}
https://www.amazon.co.jp/gp/product/4873117569/[Effective Python ―Pythonプログラムを改良する59項目^]

== Vim再入門

私が20代後半くらいの頃（今から10年以上前・・）は、仕事でも個人でもプログラミングのエディタとしてVimを使っていました。

しかし、色々なシステム開発に携わり、また時代の変化とともに、Eclipse、Visual Studio、IntelliJ IDEA、Visual Studio Codeなどの便利なIDEを利用する機会が増え、徐々にVimを使う機会が減ってきました。

[%hardbreaks]
色々なIDEを使ってきましたが、Vimの操作性に勝るものはないような気がします。
ノーマルモード、インサートモードなどのモードの概念と、ホームポジションを崩さずに書ける操作性など、Vim独特の操作に20代の頃に慣れてしまっているからかもしれません。

なので、忘れかけているVimの操作をもう一度勉強してみたいと思います。

// {{< amazon category="book" key="実践Vim 思考のスピードで編集しよう!" >}}
https://www.amazon.co.jp/gp/product/4048916599/[実践Vim^]

こちらの本は既に買って読了してますが、非常に良い本なので、これをもう１度読んで勉強し直そうと思っています。

== さいごに

色々抱負を掲げましたが、全部実践できるように頑張ります！！
