---
date: "2019-12-27"
lastmod: "2019-12-27"
slug: "changed-job"
title: "転職しました"
thumbnail: ""
description: ""
tags: ["雑記","転職","RPA","UiPath"]
archives: ["2019/12"]
---

[%hardbreaks]
前回の更新から、かなり日が経ってしまいました・・（反省）
今日は仕事納めの日ですが、、、
タイトル通り、2019年11月に転職しました。

== きっかけ

[%hardbreaks]
このブログの link:/blog/2019/07/23/start-tech-blog/[最初の記事^] でも書いたように、ソフトウェアエンジニアとしてターニングポイントな時期を迎えてると意識するようになり、色々考えて転職を決意しました。
色々というのは、年齢が40を超え、このままSES契約でプロジェクトを渡り歩くより、腰を据えて自社で開発をしたかったからです。
（待遇面に不満があったというのもありますが・・）

[%hardbreaks]
実は、そんなことをぼんやりと考えていた矢先に、常駐先企業から引き抜きのオファーを頂きました。
タイミングが絶妙すぎて、かなり驚きました。
そのオファーを受けようとも考えたりもしましたが、転職活動で色々な企業を見てみたい思いもあり（おそらく年齢的に最後の転職活動の可能性大）、オファーは一旦保留にして転職活動をしました。

== 転職活動

[%hardbreaks]
https://www.bizreach.jp/[BIZREACH^] に登録して、私の希望に沿うエージェントからのスカウトメールが来たら電話面接して案件を紹介してもらってました。
最終的には、 https://levtech.jp/[レバテック^] さんからの案件が私の希望に沿うものが多かったため、ここ１本で活動しました。
転職先企業を探すにあたって重視したのは、

* 地元福岡（市内）で働けて転勤なし
* SES業務をやってなく、自社開発
* フレックス制度があり、割と自由に働ける環境
* 少人数規模なベンチャー企業ではなく、ある程度母体が大きい企業

[%hardbreaks]
正直、ここまでの希望を満たす企業を地元福岡で探すのは結構大変でした。
ですが、担当エージェントさんのお力添えもあり、活動から約1ヶ月程度で上記を満たす企業に転職できました。

== 転職先企業

[%hardbreaks]
入社前にマネージャーと面談する機会があり、私のキャリアプランを聞かれました。
私としては、今までSES契約で開発プロジェクトに携わってきたので、TL（チームリーダー）経験はありますが、PM/PLなどのマネジメント経験がなかったため、PM/PLという立場でマネジメントしながら、実際の開発業務（設計・製造など）もやるプレイングマネージャー的なプランを描いていると伝えました。

[%hardbreaks]
転職先企業は、福岡オフィスを立ち上げて、そんなに経っているわけではないため、九州の地場企業との取引が少なく、東京側の案件を福岡に流しているニアショア的な開発を自社でやっているのが主流でした。
しかし今後は、地場企業との取引を増やしていきたい構想があるようです。
ただ、九州の地場企業の多くは、長年付き合いのあるお抱えのシステム開発ベンダーがいるため、なかなか入り込めず受注に苦戦しているようです。（他の地方企業も同様かもしれませんが）
まぁよく知らない会社に、いきなり仕事くださいって言われても無理がありますよね・・

[%hardbreaks]
そこで、ここ数年話題になっている、RPA（Robotic Process Automation）開発を皮切りに、それで信頼関係を築いて、将来的には基幹システム開発を受注していきたい構想のようです。
転職先企業はRPA開発を積極的にやっているようで、特に https://www.uipath.com/ja/[UiPath^] 社とはダイヤモンドパートナー契約を結んでいます。
それを武器に地場企業とRPA開発を受注しているようです。

[%hardbreaks]
前置きがかなり長くなりましたが、会社（マネージャー）からは、地場企業でのシステム開発においてPM/PLを目指して欲しいので、RPA開発をしばらくはやって欲しいとのことでした。
RPAは未経験でしたが、新しいことを学ぶのは好きなので、とりあえずやってみることにしました。

== 現在

[%hardbreaks]
転職して約2ヶ月が経過し、現在不満なくバリバリ開発できているかというと、実はそうではありません・・
現在の業務は、ある地場企業でUiPathを使ったRPA開発をしています。
未経験のRPA開発でしたが、まずは https://www.uipath.com/ja/rpa/academy[UiPathアカデミー^] で学習すると、UiPathの使い方がほぼ網羅できます。
（ただボリュームが大きいので、根気が必要ですが・・）
最初に使ってみた感想としては、「すごいツールだなー」でした。
ブラウザ操作、スクレイピング、Excel操作などを、ほぼノンプログラミングでできちゃうからです。
SeleniumやVBAなどで、あんなにゴリゴリコードを書いて苦労していたのがバカらしくなるくらい簡単にできてしまいます。

[%hardbreaks]
RPA開発業務に携わって2ヶ月程度ですが、すでに一人でRPA開発が出来るほど、すんなり入れました。
ただ、それは私が15年のシステム開発経験があるからだと思います。
RPA開発で重要なのは、UiPathなどのツールの使い方だけではなく、RPA化する業務システム仕様の理解だと思います。
今まで色々なシステム開発に携わってきたので、その経験が役立っていると思います。

では、このままRPA開発を続けて、最終目標である顧客の基幹システム開発受注していきたいかというと、答えは**「No」**です。

理由は、大きく２つあります。

=== RPA開発のモチベーション

[%hardbreaks]
RPA開発は、UiPathなどのツールを通して、業務操作を自動化します。
さきほども記載した通り、プログラミングは基本的にしないで（変数を扱ったり、簡単な.NETのコードは書きます）、アクティビティ（「ボタンをクリックする」とか、「Excelのセルに書き込む」とか）をフローチャートのように組み立てて、操作を自動化します。
そもそもRPAツールは、プログラミングの知識がなくても、業務処理が自動化できることを目指しています。
そのため、私のようなソフトウェアエンジニアにとっては、逆に物足りなく感じてしまい、この開発を継続していくモチベーションは保てないと思いました。

=== 客先常駐

[%hardbreaks]
現在担当しているRPA開発は、顧客の基幹WEBシステムとExcel操作がメインです。
基幹システムにアクセスするには、リモート接続できないため、客先に行って開発を行う必要があります。
Excel操作が多ければ自社で開発できますが、基幹システムでの操作がほとんどのため、結果的に客先常駐して開発しています。
（自社での開発を希望して転職したのに・・）
さらに、客先環境が居心地悪いこともあり、現在ストレスMAX状態です・・

== 今後

[%hardbreaks]
ここまでの文章だと、転職失敗だなと思われているでしょうね・・
ただ、現在の会社は、マネージャとの1on1で色々話ができる環境があるので、上記の思いは既に伝えています。
おそらく来年度には、通常の自社でのシステム開発に携われると思っています。
とりあえずは腐らずに与えられた業務を全うしたいと思います。
ただ、客先作業が嫌なので、週１程度は自社で作業して精神衛生を保つようにしますｗ

それでは、みなさん良いお年を！
